### PR TITLE
Tw104

### PR DESCRIPTION
**Pull request by c3h3**
@whizzalan 
@suensummit 

Please Review codes！

### CODE REVIEW

**Comment by suensummit** [comment]
LGTM :+1:

**Comment by suensummit** [comment]
Please move https://github.com/datasci-info/PyCrawler101-201510/blob/master/yahoo_news.ipynb to CaseStudy

**Comment by whizzalan** [comment]
OK 朕知道惹！

**Comment by suensummit** [comment]
Still OK

**Pull request merged**
